<p style="font-family:Verdana; font-size: 22px; color: cyan"> Questions on NumPy Matrix</p>

In [1]:
import numpy as np 


<p style="font-family:Verdana; font-size: 22px; color: orange"> 1. Get the maximum value from given matrix</p>

In [2]:
# Numpy matrix.max() method, we can get the maximum value from given matrix.
# make matrix with numpy
gfg = np.matrix('[64, 1; 12, 3]')
        
# applying matrix.max() method
geeks = gfg.max()
  
print(geeks)

64


In [3]:
# make a matrix with numpy
gfg2 = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]')
        
# applying matrix.max() method
geeks2 = gfg2.max()
  
print(geeks2)

9


<p style="font-family:Verdana; font-size: 22px; color: orange"> 2. Get the minimum value from given matrix</p>

In [4]:
# Numpy matrix.min() method, we can get the minimum value from given matrix.
# make matrix with numpy
gfg = np.matrix('[64, 1; 12, 3]')
        
# applying matrix.min() method
geeks = gfg.min()
  
print(geeks)


1


In [5]:
# make a matrix with numpy
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, -9]')
        
# applying matrix.min() method
geeks = gfg.min()
  
print(geeks)

-9


<p style="font-family:Verdana; font-size: 22px; color: orange"> 3. Find the number of rows and columns of a given matrix using NumPy</p>

> We can find matrix dimension with three ways:

>> Using shape Attribute
>>> Using Indexing
>>>> Using numpy.reshape()

In [6]:
# Way 1: Using .shape Attribute
matrix = np.array([[9, 9, 9], [8, 8, 8]])

dimensions = matrix.shape
rows, columns = dimensions

print("Rows:", rows)
print("Columns:", columns)

Rows: 2
Columns: 3


In [7]:
# Way 2: Using Indexing
matrix = np.array([[4, 3, 2], [8, 7, 6]])
rows = matrix.shape[0]
columns = matrix.shape[1]

print("Rows:", rows)
print("Columns:", columns)

Rows: 2
Columns: 3


In [8]:
# Way 3: Using numpy.reshape()
matrix= np.arange(1,10).reshape((3, 3))

print(matrix) # Original matrix
print(matrix.shape) # Number of rows and columns of the said matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


<p style="font-family:Verdana; font-size: 22px; color: orange"> 4. Select the elements from a given matrix</p>

> Syntax : matrix.take(index, axis)

In [9]:
# make matrix with numpy
gfg = np.matrix('[4, 1, 12, 3, 4, 6, 7]')
            
# applying matrix.take() method
geek = gfg.take(2)
  
print(geek)

[[12]]


In [ ]:
# make matrix with numpy
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
            
# applying matrix.take() method
geek = gfg.take(0, 1)
  
print(geek)

[[ 4 12  4]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 5. Find the sum of values in a matrix</p>

> Syntax :   matrix.sum()

In [13]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
           
# applying matrix.sum() method
geek = gfg.sum()
 
print(geek)

20


In [18]:
# make matrix with numpy
gfg = np.matrix('[4, 1, 9; 11, 11, 11; 4, 5, 6]')
           
# applying matrix.sum() method
geek = gfg.sum(axis = 1)
 
print(geek)

[[14]
 [33]
 [15]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 6. Calculate the sum of the diagonal elements of a NumPy array</p>

> Syntax : numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)  

In [20]:
# Example 1: For 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)


Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]


In [21]:
# calculating the Trace of a matrix
trace = np.trace(n_array)


print("\nTrace of given 3X3 matrix:")
print(trace)


Trace of given 3X3 matrix:
176


In [22]:
# Example 2: For 4X4 Numpy matrix
# creating a 4X4 Numpy matrix
n_array = np.array([[55, 25, 15, 41],
                    [30, 44, 2, 54],
                    [11, 45, 77, 11],
                    [11, 212, 4, 20]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

Numpy Matrix is:
[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]


In [23]:
# calculating the Trace of a matrix
trace = np.trace(n_array)


print("\nTrace of given 4X4 matrix:")
print(trace)


Trace of given 4X4 matrix:
196


>> numpy.diagonal(a, offset=0, axis1=0, axis2=1)

In [24]:
# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# Finding the diagonal elements of a matrix
diag = np.diagonal(n_array)

print("\nDiagonal elements are:")
print(diag)

print("\nSum of Diagonal elements is:")
print(sum(diag))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Diagonal elements are:
[55 44 77]

Sum of Diagonal elements is:
176


<p style="font-family:Verdana; font-size: 22px; color: orange"> 7. Adding and Subtracting Matrices in Python</p>

In [25]:
# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [26]:

# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 8. Ways to add row/columns in numpy array</p>

> Method 1: Using np.append()

In [27]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# printing initial array
print("initial_array : ", str(ini_array));

# Array to be added as column
column_to_be_added = np.array([[1], [2], [3]])

# Adding column to array using append() method
arr = np.append(ini_array, column_to_be_added, axis=1)

# printing result
print ("resultant array", str(arr))

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


>> Method 2: Using np.concatenate

In [28]:
# Adding column to array using append() method
arr = np.concatenate([ini_array, column_to_be_added], axis=1)


# printing result
print ("resultant array", str(arr))

resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


>>> Method 3: Using np.insert()

In [29]:
# Adding column to array using append() method
arr = np.insert(ini_array, 0, column_to_be_added, axis=1)


# printing result
print ("resultant array", str(arr))

resultant array [[ 1  2  3  1  2  3]
 [ 1  2  3 45  4  7]
 [ 1  2  3  9  6 10]]


>> Method 4: Using np.hstack()   

In [31]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# Array to be added as column
column_to_be_added = np.array([1, 2, 3])

# Adding column to numpy array
result = np.hstack((ini_array, np.atleast_2d(column_to_be_added).T))

# printing result
print ("resultant array", str(result))

resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


> Method 5: Using np.column_stack()  

In [32]:

ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# Array to be added as column
column_to_be_added = np.array([1, 2, 3])

# Adding column to numpy array
result = np.column_stack((ini_array, column_to_be_added))

# printing result
print ("resultant array", str(result))

resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 9. Matrix Multiplication in NumPy</p>

> using the numpy.dot() method

In [33]:

# creating two matrices
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print("Matrix p :")
print(p)
print("Matrix q :")
print(q)

Matrix p :
[[1, 2], [2, 3]]
Matrix q :
[[4, 5], [6, 7]]


In [34]:

# computing product
result = np.dot(p, q)

# printing the result
print("The matrix multiplication is :")
print(result)

The matrix multiplication is :
[[16 19]
 [26 31]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 10. Get the eigen values of a matrix</p>

> syntax : np.eigvals(matrix)

In [35]:
# import numpy
from numpy import linalg as LA

# using np.eigvals() method
gfg = LA.eigvals([[1, 2], [3, 4]])

print(gfg)

[-0.37228132  5.37228132]


In [36]:

# using np.eigvals() method
gfg = LA.eigvals([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(gfg)

[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]
