<p style="font-family:Verdana; font-size: 22px; color: cyan"> Questions on NumPy Matrix</p>

In [2]:
import numpy as np 


<p style="font-family:Verdana; font-size: 22px; color: orange"> 11. How to Calculate the determinant of a matrix using NumPy?</p>

> Using numpy.linalg.slotdet()

In [3]:
A = np.array([[50, 29], [30, 44]])
sign, logdet = np.linalg.slogdet(A)
res = sign * np.exp(logdet)

print(res)

1330.0000000000002


In [ ]:
# Explanation: np.linalg.slogdet(A) returns sign (the determinant's sign) and logdet (the log of its absolute value). 
# 
# The determinant is computed as sign * np.exp(logdet), ensuring numerical stability.

<p style="font-family:Verdana; font-size: 22px; color: orange"> 12. How to inverse a matrix using NumPy</p>

> Syntax: numpy.linalg.inv(a)

In [4]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 13. How to count the frequency of unique values in NumPy array?</p>

* Using the np.unique() Function
> Using NumPy Unique Frequency
>> Using NumPy in Transpose Form
>>> Using numpy.bincount()
>>>> Using the collections.Counter() Function

In [5]:
ini_array = np.array([10, 20, 5,
                      10, 8, 20,
                      8, 9])

# Get a tuple of unique values 
# and their frequency in
# numpy array
unique, frequency = np.unique(ini_array, 
                              return_counts = True)
# print unique values array
print("Unique Values:", 
      unique)

# print frequency array
print("Frequency Values:",
      frequency)

Unique Values: [ 5  8  9 10 20]
Frequency Values: [1 2 1 2 2]


In [6]:
# Get a tuple of unique values 
# and their frequency 
# in numpy array
unique, frequency = np.unique(ini_array,
                              return_counts = True) 

# convert both into one numpy array
count = np.asarray((unique, frequency ))

print("The values and their frequency are:\n",
     count)

The values and their frequency are:
 [[ 5  8  9 10 20]
 [ 1  2  1  2  2]]


In [7]:
# create a 1d-array
ini_array = np.array([10, 20, 5,
                      10, 8, 20,
                      8, 9])

# Get a tuple of unique values 
# and their frequency in
# numpy array
unique, frequency = np.unique(ini_array, 
                              return_counts = True) 

# convert both into one numpy array 
# and then transpose it
count = np.asarray((unique,frequency )).T

print("The values and their frequency are in transpose form:\n",
     count)

The values and their frequency are in transpose form:
 [[ 5  1]
 [ 8  2]
 [ 9  1]
 [10  2]
 [20  2]]


In [8]:
# Create a 1D array
arr = np.array([10, 20, 5, 10, 8, 20, 8, 9])

# Get unique values and their counts using bincount
unique_values = np.unique(arr)
counts = np.bincount(arr)

# Display the results
print("\nMethod 2:")
print("Unique Values:", unique_values)
print("Counts:", counts[unique_values])


Method 2:
Unique Values: [ 5  8  9 10 20]
Counts: [1 2 1 2 2]


In [10]:
from collections import Counter

# Create a list
my_list = [10, 20, 5, 10, 8, 20, 8, 9]

# Use Counter to count occurrences
counts = Counter(my_list)

# Display the results
print("Unique Values:", list(counts.keys()))
print("Counts:", list(counts.values()))

Unique Values: [10, 20, 5, 8, 9]
Counts: [2, 2, 1, 2, 1]
