<p style="font-family:Verdana; font-size: 22px; color: cyan"> Questions on NumPy Array</p>

In [1]:
import numpy as np 


<p style="font-family:Verdana; font-size: 22px; color: orange"> 1. How to create an empty and a full NumPy array?</p>

In [2]:
# Create an empty array of shape (3, 4)
empty_array = np.empty((3, 4))
print("Empty Array:\n", empty_array)

Empty Array:
 [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 1.51038982e+160]]


In [3]:
# Create a full array of shape (3, 3) filled with the value 5
full_array = np.full((3, 3), 5)
print("Full Array:\n", full_array)

Full Array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 2. Create a Numpy array filled with all zeros - Python</p>

In [4]:
# Create a 1D array of zeros with 5 elements
array_1d = np.zeros(5)
print(array_1d)

[0. 0. 0. 0. 0.]


> By default, the data type of the array is float, so the zeros are represented as 0.0.

In [5]:
# Create a 2D array of zeros (3 rows, 4 columns)
array_2d = np.zeros((3, 4))
print(array_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Create an integer zero array
array_int = np.zeros((2, 3), dtype=int)
print(array_int)

[[0 0 0]
 [0 0 0]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 3. Create a Numpy array filled with all ones</p>

In [7]:
array = np.ones(5)
print(array)

[1. 1. 1. 1. 1.]


> 2D Array of Ones

In [8]:
# Create a 2D array of ones (3 rows, 4 columns)
ones_array_2d = np.ones((3, 4))
print(ones_array_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


>> Array with a Specific Data Type

In [9]:
# Create an integer array of ones with 4 elements
ones_int_array = np.ones(4, dtype=int)
print(ones_int_array)

[1 1 1 1]


>>> Multi-Dimensional Array of Ones

In [10]:
# Create a 3D array of ones with shape (2, 3, 4)
ones_array_3d = np.ones((2, 3, 4))
print(ones_array_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 4. Check whether a Numpy array contains a specified row</p>

> Syntax: ndarray.tolist()

In [11]:
# create numpy array
arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])

# view array
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

True
False
False
True


<p style="font-family:Verdana; font-size: 22px; color: orange"> 5. How to Remove rows in Numpy array that contains non-numeric values?</p>

> using the np.isnan() function along with the Bitwise NOT operator

In [13]:
# Creating a 2x3 2-D NumPy array
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]


In [16]:
print("\nRemove all rows containing NaN values:")
cleaned_arr = n_arr[~np.isnan(n_arr).any(axis=1)]
print(cleaned_arr)


Remove all rows containing NaN values:
[[10.5 22.5  3.8]]


In [17]:
# Creating a 3x3 2-D NumPy array
n_arr = np.array([[10.5, 22.5, 3.8], 
                  [23.45, 50, 78.7],
                  [41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

Given array:
[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]
 [41.     nan   nan]]


In [18]:
print("\nRemove all rows containing NaN values:")
cleaned_arr = n_arr[~np.isnan(n_arr).any(axis=1)]
print(cleaned_arr)


Remove all rows containing NaN values:
[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]]


In [19]:
# Creating a 5x4 2-D NumPy array
n_arr = np.array([[10.5, 22.5, 3.8, 5],
                  [23.45, 50, 78.7, 3.5],
                  [41, np.nan, np.nan, 0],
                  [20, 50.20, np.nan, 2.5],
                  [18.8, 50.60, 8.8, 58.6]])

print("Given array:")
print(n_arr)

Given array:
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [41.     nan   nan  0.  ]
 [20.   50.2    nan  2.5 ]
 [18.8  50.6   8.8  58.6 ]]


In [20]:
print("\nRemove all rows containing NaN values:")
cleaned_arr = n_arr[~np.isnan(n_arr).any(axis=1)]
print(cleaned_arr)


Remove all rows containing NaN values:
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [18.8  50.6   8.8  58.6 ]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 6. Remove single-dimensional entries from the shape of an array</p>

<p style="font-family:Verdana; font-size: 22px; color: orange"> numpy.squeeze() in Python</p>

In [21]:

in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])
 
print ("Input array : ", in_arr) 
print("Shape of input array : ", in_arr.shape)  

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)


In [22]:
out_arr = np.squeeze(in_arr) 

print ("output squeezed array : ", out_arr)
print("Shape of output array : ", out_arr.shape) 

output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


>> Example 1: Using the axis parameter to squeeze a specific dimension

In [25]:
in_arr = np.arange(9).reshape(1, 3, 3) 
print ("Input array : ", in_arr)  

Input array :  [[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [27]:
out_arr = np.squeeze(in_arr, axis = 0) 

print ("output array : ", out_arr)  
print("The shapes of Input and Output array : ") 
print(in_arr.shape, "-->", out_arr.shape)

output array :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
The shapes of Input and Output array : 
(1, 3, 3) --> (3, 3)


>> Example 3: Error when trying to squeeze a non-singleton dimension

In [28]:
in_arr = np.arange(9).reshape(1, 3, 3)
print("Input array: ", in_arr)  

Input array:  [[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [30]:

# Trying to squeeze the axis that doesn't have size 1
try:
    out_arr = np.squeeze(in_arr, axis=1)  
except ValueError as e:
    print("Error: ", e)

# Explanation: The input array has a shape of (1, 3, 3). The attempt to squeeze axis = 1, 
# which corresponds to the second dimension with size 3, 
# results in a ValueError, as the dimension is not of size 1.

Error:  cannot select an axis to squeeze out which has size not equal to one


<p style="font-family:Verdana; font-size: 22px; color: orange"> 7. Find the number of occurrences of a sequence in a NumPy array</p>

In [34]:
# create numpy array
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

# Counting sequence
output = repr(arr).count("9, 4")

# view output
print(output)

4


<p style="font-family:Verdana; font-size: 22px; color: orange"> 8. Find the most frequent value in a NumPy array</p>

> Example 1: Apply bincount() method

In [35]:
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


> Example 2: If the array has more than one element having maximum frequency

In [37]:
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print("Original array:")
print(x)

print("Most frequent value in above array")
y = np.bincount(x)
maximum = max(y)
for i in range(len(y)):
    if y[i] == maximum:
        print(i, end=" ")

Original array:
[1 1 1 2 3 4 2 4 3 3]
Most frequent value in above array
1 3 

<p style="font-family:Verdana; font-size: 22px; color: orange"> 9. Combining a one and a two-dimensional NumPy Array</p>

> Syntax: numpy.nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

In [38]:
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)


One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
# Combine 1-D and 2-D arrays and display 
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


In [40]:
num_1d = np.arange(7)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(21).reshape(3,7)
print("\nTwo dimensional array:")
print(num_2d)

One dimensional array:
[0 1 2 3 4 5 6]

Two dimensional array:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [41]:
# Combine 1-D and 2-D arrays and display 
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

0:0
1:1
2:2
3:3
4:4
5:5
6:6
0:7
1:8
2:9
3:10
4:11
5:12
6:13
0:14
1:15
2:16
3:17
4:18
5:19
6:20


In [42]:
num_1d = np.arange(2)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(12).reshape(6,2)
print("\nTwo dimensional array:")
print(num_2d)


One dimensional array:
[0 1]

Two dimensional array:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [43]:
# Combine 1-D and 2-D arrays and display
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)


0:0
1:1
0:2
1:3
0:4
1:5
0:6
1:7
0:8
1:9
0:10
1:11


<p style="font-family:Verdana; font-size: 22px; color: orange"> 10. How to build an array of all combinations of two NumPy arrays?</p>


> numpy.meshgrid(*xi, copy=True, sparse=False, indexing='xy')

>> Example 1: Computing combinations of elements of Two NumPy arrays

In [44]:
a = np.array([1, 2])
b = np.array([4, 6])

print("Array-1")
print(a)

print("\nArray-2")
print(b)

Array-1
[1 2]

Array-2
[4 6]


In [45]:
res = np.array(np.meshgrid(a, b)).T.reshape(-1, 2)

print("\nCombine array:")
print(res)


Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]


>>> Example 2: Computing combinations of elements of Three NumPy arrays

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 6, 4])
c = np.array([3, 6])

print("Array-1")
print(a)

print("Array-2")
print(b)

print("Array-3")
print(c)

Array-1
[1 2 3]
Array-2
[4 6 4]
Array-3
[3 6]


In [47]:
res = np.array(
  np.meshgrid(a, b, c)).T.reshape(-1, 3)

print("\nCombine array:")
print(res)


Combine array:
[[1 4 3]
 [1 6 3]
 [1 4 3]
 [2 4 3]
 [2 6 3]
 [2 4 3]
 [3 4 3]
 [3 6 3]
 [3 4 3]
 [1 4 6]
 [1 6 6]
 [1 4 6]
 [2 4 6]
 [2 6 6]
 [2 4 6]
 [3 4 6]
 [3 6 6]
 [3 4 6]]


> Example 3: Computing combinations of elements of Four NumPy arrays

In [48]:
a = np.array([50, 21])
b = np.array([4, 4])
c = np.array([1, 10])
d = np.array([7, 14])


print("Array-1")
print(a)

print("Array-2")
print(b)

print("Array-3")
print(c)

print("Array-4")
print(d)


Array-1
[50 21]
Array-2
[4 4]
Array-3
[ 1 10]
Array-4
[ 7 14]


In [49]:
res = np.array(np.meshgrid(a, b, c, d)).T.reshape(-1, 4)

print("\nCombine array:")
print(res)


Combine array:
[[50  4  1  7]
 [50  4  1  7]
 [21  4  1  7]
 [21  4  1  7]
 [50  4 10  7]
 [50  4 10  7]
 [21  4 10  7]
 [21  4 10  7]
 [50  4  1 14]
 [50  4  1 14]
 [21  4  1 14]
 [21  4  1 14]
 [50  4 10 14]
 [50  4 10 14]
 [21  4 10 14]
 [21  4 10 14]]
