<p style="font-family:Verdana; font-size: 22px; color: cyan"> Questions on NumPy Array</p>

In [3]:
import numpy as np 


<p style="font-family:Verdana; font-size: 22px; color: orange"> 11. How to compare two NumPy arrays?</p>

> Method 1: We generally use the == operator to compare two NumPy arrays to generate a new array object. 

In [8]:
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)

True


>> Method 2: We can also use greater than, less than and equal to operators to compare.

In [10]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a: ", a)
print("Array b: ", b)

Array a:  [101  99  87]
Array b:  [897  97 111]


In [11]:
print("a > b")
print(np.greater(a, b))

a > b
[False  True False]


In [12]:
print("a >= b")
print(np.greater_equal(a, b))

a >= b
[False  True False]


In [13]:
print("a < b")
print(np.less(a, b))

a < b
[ True False  True]


In [14]:
print("a <= b")
print(np.less_equal(a, b))

a <= b
[ True False  True]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 12. How to check whether specified values are present in NumPy array?</p>

>  "in" operator is used to check whether certain element and values are present in a given sequence and hence return Boolean values 'True" and "False".

In [15]:
# creating a Numpy array
n_array = np.array([[2, 3, 0],
                    [4, 1, 6]])

print("Given array:")
print(n_array)


Given array:
[[2 3 0]
 [4 1 6]]


In [16]:
# Checking whether specific values
# are present in "n_array" or not
print(2 in n_array)
print(0 in n_array)
print(6 in n_array)
print(50 in n_array)
print(10 in n_array)

True
True
True
False
False


<p style="font-family:Verdana; font-size: 22px; color: orange"> 13. Flatten a Matrix in Python using NumPy</p>

> By using ndarray.flatten() function we can flatten a matrix to one dimension in python.

In [17]:
# declare matrix with np
gfg = np.array([[2, 3], [4, 5]])

# using array.flatten() method
flat_gfg = gfg.flatten()
print(flat_gfg)

[2 3 4 5]


In [18]:
# declare matrix with np
gfg = np.array([[6, 9], [8, 5], [18, 21]])

# using array.flatten() method
gfg.flatten()

array([ 6,  9,  8,  5, 18, 21])

In [19]:
# declare matrix with np
gfg = np.array([[6, 9, 12], [8, 5, 2], [18, 21, 24]])

# using array.flatten() method
flat_gfg = gfg.flatten(order='A')
print(flat_gfg)

[ 6  9 12  8  5  2 18 21 24]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 14. Counts the number of non-zero values in the array</p>

> Syntax  :  numpy.count_nonzero(arr, axis=None)

In [20]:
arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7]]

gfg = np.count_nonzero(arr)

print (gfg)

6


In [24]:
arr = [[0, 1, 2, 3, 4], [5, 0, 6, 0, 7]]

gfg = np.count_nonzero(arr, axis = 0)

print (gfg)

[1 1 2 1 2]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 15. Count the number of elements along a given axis</p>

> numpy.size() function in Python is used to count the number of elements in a NumPy array.


>> 1. To Find Total Number of Elements

In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.size(arr))

8


>> 2. To Count the Elements Along a Specific Axis

In [28]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
    ])
# Here 0 is used to denote the axis as rows and 1 is used to denote axis as columns. 
print(np.size(arr, 0)) # Therefore np.size(arr, 0) will returns the number of rows 
print(np.size(arr, 1)) # and np.size(arr, 1) returns the number of columns.

2
4


>>> 3. To Count Elements in a 3D Array
* axis=0 refers to the number of blocks (first level of depth).
* axis=1 refers to the number of rows in each block.
* axis=2 refers to the number of columns in each row.

In [30]:
arr = np.array([
    [
        [1, 2],
        [1, 2], 
        [3, 4]
    ],
    [
        [5, 6],
        [1, 2], 
        [7, 8]
    ]
                ])

print(np.size(arr)) 
print(np.size(arr, 0))    
print(np.size(arr, 1))
print(np.size(arr, 2))

12
2
3
2


<p style="font-family:Verdana; font-size: 22px; color: orange"> 16. Reverse a numpy array</p>

> Using flip() function to Reverse a Numpy array

In [31]:
# The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# using shortcut method to reverse
res = np.flip(ini_array)

# printing result
print("final array", str(res))

final array [5 4 6 3 2 1]


>> Using the list slicing method to reverse a Numpy array

In [32]:

# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# printing initial ini_array
print("initial array", str(ini_array))


initial array [1 2 3 6 4 5]


In [33]:
# printing type of ini_array
print("type of ini_array", type(ini_array))

# using shortcut method to reverse
res = ini_array[::-1]

# printing result
print("final array", str(res))

type of ini_array <class 'numpy.ndarray'>
final array [5 4 6 3 2 1]


>> Using flipud function to Reverse a Numpy array 

In [34]:
# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# printing initial ini_array
print("initial array", str(ini_array))

# printing type of ini_array
print("type of ini_array", type(ini_array))

# using flipud method to reverse
res = np.flipud(ini_array)

# printing result
print("final array", str(res))

initial array [1 2 3 6 4 5]
type of ini_array <class 'numpy.ndarray'>
final array [5 4 6 3 2 1]
