<p style="font-family:Verdana; font-size: 26px; color: orange"> Different Ways to Create Numpy Arrays in Python</p>

<p style="font-family:Verdana; font-size: 22px; color: orange"> Create Numpy Arrays Using Lists or Tuples</p>

In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
numpy_array = np.array(my_list)
print("Simple NumPy Array:",numpy_array)

Simple NumPy Array: [1 2 3 4 5]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Initialize a Python NumPy Array Using Special Functions</p>

> np.zeros(): Creates an array filled with zeros.
>> np.ones(): Creates an array filled with ones.
>>> np.full(): Creates an array filled with a specified value.
>>>> np.arange(): Creates an array with values that are evenly spaced within a given range.
>>>>> np.linspace(): Creates an array with values that are evenly spaced over a specified interval.

In [2]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
constant_array = np.full((2, 2), 7)
range_array = np.arange(0, 10, 2)  # start, stop, step
linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Create Python Numpy Arrays Using Random Number Generation</p>


> np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
>> np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.
>>> np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.

In [8]:
random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 2)
randint_array = np.random.randint(0, 20, size=(2, 3)) 

print(random_array, "\n\n\n", normal_array, "\n\n\n", randint_array) 
# print(before, "\n\n\n", after)

[[0.49802156 0.58888652 0.41367246]
 [0.21109832 0.03959567 0.72854438]] 


 [[-0.23802678  1.85919735]
 [ 0.87824248 -0.461166  ]] 


 [[12 14 14]
 [ 1 16  3]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Create Python Numpy Arrays Using Matrix Creation Routines</p>


> np.eye(): Creates an identity matrix of specified size.
>> np.diag(): Constructs a diagonal array.
>>> np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.
>>>> np.ones_like(): Creates an array of ones with the same shape and type as a given array.

In [13]:
identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print('identity_matrix', "\n", identity_matrix, "\n")
print('diagonal_array', "\n", diagonal_array, "\n")
print('zeros_like_array', "\n", zeros_like_array, "\n")
print('ones_like_array', "\n", ones_like_array)

identity_matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

diagonal_array 
 [[1 0 0]
 [0 2 0]
 [0 0 3]] 

zeros_like_array 
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 

ones_like_array 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
