<p style="font-family:Verdana; font-size: 22px; color: cyan"> Numpy Array Indexing</p>

In [1]:
import numpy as np 

<p style="font-family:Verdana; font-size: 22px; color: orange"> 1. Accessing Elements in 1D Arrays</p>

In [3]:
#  A 1D NumPy array is a sequence of values with positions called indices which starts at 0.
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

10


<p style="font-family:Verdana; font-size: 22px; color: orange"> 2. Accessing Elements in Multidimensional Arrays</p>

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])

6


In [5]:
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])

16


<p style="font-family:Verdana; font-size: 22px; color: orange"> 3. Slicing Arrays</p>

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5])

print(arr[1:4])

[1 2 3]


In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing Multidimensional Arrays: In this slicing can be applied to each dimension separately
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 4. Boolean Indexing</p>

In [9]:
arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])

[25 30]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 5. Fancy Indexing</p>

In [11]:
arr = np.array([10, 20, 30, 40, 50])
# It is also known as Advanced Indexing which allows us access elements of an array 
# by using another array or list of indices. 
indices = [0, 2, 4]
print(arr[indices])

[10 30 50]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 6. Integer Array Indexing</p>

In [13]:
arr = np.array([1, 2, 3, 4, 5])
# It is similar to fancy indexing and uses an array of integers to select multiple elements from another array. 
print(arr[[0, 2, 4]])

[1 3 5]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 7. Ellipsis (...) in Indexing</p>

In [14]:
# The ellipsis (...) can be used to select all dimensions which are not explicitly mentioned. 
cube = np.random.rand(4, 4, 4)

print(cube[..., 0])

[[0.80813609 0.31215591 0.87430322 0.46975419]
 [0.92045271 0.3700782  0.84829624 0.9796303 ]
 [0.43564133 0.60558605 0.7233169  0.7231755 ]
 [0.64373363 0.30946383 0.80538392 0.30566866]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 8. Using np.newaxis to Add New Dimensions</p>

In [15]:
# The np.newaxis keyword adds a new axis to the array which helps in converting a 1D array into a row or column vector.
arr = np.array([1, 2, 3])

print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 9. Modifying Array Elements</p>

In [16]:
arr = np.array([1, 2, 3, 4])
# We can modify array elements directly by using indexing or slicing.
arr[1:3] = 99

print(arr)

[ 1 99 99  4]
