<p style="font-family:Verdana; font-size: 22px; color: cyan"> numpy.stack() in Python</p>

In [2]:
import numpy as np 

<p style="font-family:Verdana; font-size: 22px; color: orange"> 1. Important points:</p>

> stack() is used for joining multiple NumPy arrays. Unlike, concatenate(), it joins arrays along a new axis. It returns a NumPy array.
>> to join 2 arrays, they must have the same shape and dimensions. (e.g. both (2,3)--> 2 rows,3 columns)
>>> stack() creates a new array which has 1 more dimension than the input arrays. If we stack 2 1-D arrays, the resultant array will have 2 dimensions.


<p style="font-family:Verdana; font-size: 22px; color: orange"> Example #1 : stacking two 1d arrays</p>

In [3]:
# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b),axis=0)
print(c)

[[1 2 3]
 [4 5 6]]


> Notice, output is a 2-D array. They are stacked row-wise. Now, let's change the axis to 1.

In [5]:
# stack 2 1-d arrays column-wise
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

<p style="font-family:Verdana; font-size: 22px; color: orange"> Example #2 : stacking two 2d arrays</p>

In [7]:
# input arrays
x=np.array([[1,2,3],
            [4,5,6]])

y=np.array([[7,8,9],
            [10,11,12]])

In [8]:
# 1. stacking with axis=0
np.stack((x,y),axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
# 2. stacking with axis=1
np.stack((x,y),axis=1)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [11]:
# 3. stacking with axis =2
np.stack((x,y),axis=2)

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

<p style="font-family:Verdana; font-size: 22px; color: orange"> Example #2 : stacking more than two 2d arrays</p>

In [13]:
# 1. with axis=0 : Just stacking. 
x=np.array([[1,2,3],
            [4,5,6]])
y=np.array([[7,8,9],
            [10,11,12]])
z=np.array([[13,14,15],
            [16,17,18]])

np.stack((x,y,z),axis=0)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
# 2. with axis =1 (row-wise stacking)
np.stack((x,y,z),axis=1)

array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18]]])

In [15]:
# 3. with axis =2 (column-wise stacking)
np.stack((x,y,z),axis=2)

array([[[ 1,  7, 13],
        [ 2,  8, 14],
        [ 3,  9, 15]],

       [[ 4, 10, 16],
        [ 5, 11, 17],
        [ 6, 12, 18]]])

<p style="font-family:Verdana; font-size: 22px; color: orange"> Example #3 : stacking two 3d arrays</p>

In [16]:
# 1. axis=0. Just stacking
#2 input 3d arrays

m=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],

            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

n=np.array([[[51,52,53],
            [54,55,56],
            [57,58,59]],

            [[110,111,112],
            [113,114,115],
            [116,117,118]]])

# stacking
np.stack((m,n),axis=0)

array([[[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 10,  11,  12],
         [ 13,  14,  15],
         [ 16,  17,  18]]],


       [[[ 51,  52,  53],
         [ 54,  55,  56],
         [ 57,  58,  59]],

        [[110, 111, 112],
         [113, 114, 115],
         [116, 117, 118]]]])

In [17]:
# 2. with axis=1 
np.stack((m,n),axis=1)

array([[[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 51,  52,  53],
         [ 54,  55,  56],
         [ 57,  58,  59]]],


       [[[ 10,  11,  12],
         [ 13,  14,  15],
         [ 16,  17,  18]],

        [[110, 111, 112],
         [113, 114, 115],
         [116, 117, 118]]]])

In [18]:
# 3. with axis = 2 
np.stack((m,n),axis=2)

array([[[[  1,   2,   3],
         [ 51,  52,  53]],

        [[  4,   5,   6],
         [ 54,  55,  56]],

        [[  7,   8,   9],
         [ 57,  58,  59]]],


       [[[ 10,  11,  12],
         [110, 111, 112]],

        [[ 13,  14,  15],
         [113, 114, 115]],

        [[ 16,  17,  18],
         [116, 117, 118]]]])

In [19]:
# 4. with axis = 3
np.stack((m,n),axis=3)


array([[[[  1,  51],
         [  2,  52],
         [  3,  53]],

        [[  4,  54],
         [  5,  55],
         [  6,  56]],

        [[  7,  57],
         [  8,  58],
         [  9,  59]]],


       [[[ 10, 110],
         [ 11, 111],
         [ 12, 112]],

        [[ 13, 113],
         [ 14, 114],
         [ 15, 115]],

        [[ 16, 116],
         [ 17, 117],
         [ 18, 118]]]])