<p style="font-family:Verdana; font-size: 22px; color: cyan"> NumPy Array Broadcasting</p>

In [1]:
import numpy as np 

<p style="font-family:Verdana; font-size: 22px; color: orange"> Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. </p>

> It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. 
>> This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops.  

In [2]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  
scalar = 10  

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 1. Important points:</p>

> Check Dimensions: Ensure the arrays have the same number of dimensions or expandable dimensions.
>> Dimension Padding: If arrays have different numbers of dimensions the smaller array is left-padded with ones.
>>> Shape Compatibility: Two dimensions are compatible if they are equal or one of them is 1.

<p style="font-family:Verdana; font-size: 22px; color: orange"> Example 1: Broadcasting a Scalar to a 1D Array</p>


In [3]:
arr = np.array([1, 2, 3])

res = arr + 1  
print(res)

[2 3 4]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Example 2: Broadcasting a 1D Array to a 2D Array</p>

In [4]:
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Example 3: Broadcasting in Conditional Operations</p>

In [5]:
ages = np.array([12, 24, 35, 45, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


<p style="font-family:Verdana; font-size: 22px; color: orange"> Example 4: Using Broadcasting for Matrix Multiplication</p>

In [6]:
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Example 5: Scaling Data with Broadcasting</p>

In [7]:
food_data = np.array([[0.8, 2.9, 3.9], 
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])

caloric_values = np.array([3, 3, 8]) 

caloric_matrix = caloric_values 

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Example 6: Adjusting Temperature Data Across Multiple Locations</p>

In [8]:
temperatures = np.array([
    [30, 32, 34, 33, 31],  
    [25, 27, 29, 28, 26], 
    [20, 22, 24, 23, 21]  
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


<p style="font-family:Verdana; font-size: 22px; color: orange"> Example 7: Normalizing Image Data</p>

In [9]:
data = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])

feature_mean = data.mean(axis=0)

centered_data = data - feature_mean
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
