<p style="font-family:Verdana; font-size: 22px; color: cyan"> NumPy - Arithmetic Operations</p>

In [1]:
import numpy as np 

<p style="font-family:Verdana; font-size: 22px; color: orange"> 1. Addition of Arrays</p>

> using the np.add() function.

In [2]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = np.add(a, b)
print(add_ans)

[  7  77  23 130]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 2. Subtraction of Arrays</p>

> We can subtract two arrays element-wise using the np.subtract() function. 

In [3]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 3. Multiplication of Arrays</p>

> Multiplication in NumPy can be done element-wise using the np.multiply() function.

In [5]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 4. Division of Arrays</p>

> that is performed element-wise using the np.divide() function. 

In [6]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 5. Exponentiation (Power)</p>

> In NumPy, this can be done using the np.power() function.

In [7]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 3, 2])

pow_ans = np.power(a, b)
print(pow_ans)

[        25 1934917632       2197      10000]


<p style="font-family:Verdana; font-size: 22px; color: orange"> 6. Modulus Operation</p>

> It finds the remainder when one number is divided by another. In NumPy, you can use the np.mod() function

In [8]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]


In [ ]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]
